name: SSB-DiscordStatistics
version: ${project.version}
author: Ome_R
description: Discord statistics integration to your SuperiorSkyblock!
main: com.bgsoftware.ssbdiscordstatistics.SSBDiscordStatisticsPlugin
website: https://bg-software.com/

depend:
  - SuperiorSkyblock2
  - DiscordSRV